services:
    node:
        build: .
        command: "npm run start"
        working_dir: /node/app
        environment:
            - NODE_ENV=development
        expose:
            -   "3001"
        ports:
            -   "3001:3001"
        volumes:
            -   .:/node/app
    db-chat:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=chat
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            -   "3309:3306"
        volumes:
            -   ./mysql:/var/lib/mysql