
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8989:80"
    volumes:
      - "./backend:/var/www"
    networks:
      - default
    depends_on:
      - db
    links:
      - db
  db:
    image: "mysql:8.0"
    container_name: db
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_HOST: "${DB_HOST:-localhost}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-password}"
      MYSQL_DATABASE: "${DB_DATABASE:-laravel}"
      MYSQL_USER: "${DB_USERNAME:-root}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secretpassword}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    volumes:
      - "/var/lib/mysql"
      - "sail-mysql:/var/lib/mysql"
      - "./apache/:/docker-entrypoint-initdb.d"
      # - /var/www/storage/app/public/imagens:/var/www/storage/app/public/imagens
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PASSWORD=1234
    links:
      - db
    networks:
      - default
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--host"]
    networks:
      - default
networks:
  sail:
    driver: bridge
  default:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
